openapi: 3.0.0

info: 
  title: Backend Project Node
  description: Production Ready Backend
  version: 1.0.1

servers:
  - url: http://localhost:4000/api/v1
    description: Api Working on LocalHost 4000
  - url: https://test-backend-demo.onrender.com/api/v1/linkedIn
    description: Api Hosted on Render Server and are live, one of the endpoint is mentioned above